### ISSUE TITLE
put_object_stream sync implementation does not report errors for small uploads

### ISSUE THREAD

**Issue by jccallu-genomicsplc** [durch/rust-s3#335]
**Describe the bug**

For small uploads (below the CHUNK_SIZE), the sync implementation in `_put_object_stream_with_content_type` first initiates a multipart upload, then aborts it and runs a standalone call to `put_object` (see https://github.com/durch/rust-s3/blob/v0.32.0/s3/src/bucket.rs#L1047)

The returned response code is the one from the initial multipart upload initiation, whereas a client of the crate would expect to receive the response from the final call to `put_object`

**To Reproduce**

This is a problem in case of spurious network errors which won't be easy to reproduce, but fixing it should be as simple as  returning the response code from `put_object` after it is called.

**Expected behavior**

In case of spurious network errors during put_object_stream, the last failed response code should be returned 

**Environment**
 - Rust version: `1.67`
 - lib version `0.30.0`

**Additional context**
-

**Comment by durch** [comment]
Fixed as of at least `0.33`

**Comment by jccallu-genomicsplc** [comment]
> Fixed as of at least `0.33`

Thanks @durch for looking into this and handling other issues since 0.32.

I'm afraid this bug is still present in the master branch here: https://github.com/durch/rust-s3/blob/7fdb685d71385152198f906068f15faaabd28592/s3/src/bucket.rs#L1193

At this line the function should always return a Result and not continue in case of success. Currently this means we will try to read more from the reader, and presumably return an error because of this. This makes the function entirely unstable for small objects.

The behaviour originally described in the bug is now slightly different, but still broken. @durch, can you re-open this issue or should it be rewritten in a new one?
